In [37]:
import torch
import torch.nn as nn

In [38]:
class MyDropout:
    def __init__(self, p=0.5):
        if not 0 <= p <= 1:
            raise ValueError("p must be between 0 and 1")
        self.p = p
        self.training = True # this is default

    def train(self):
        self.training = True

    def eval(self):
        self.training = False

    def __call__(self, x):
        if not self.training or self.p == 0.0: # that means the model is at test time
            return x

        mask = (torch.rand_like(x) > p).float()
        return (mask * x) / (1.0 - self.p)

In [39]:
myd = MyDropout(p=0.3)
d = nn.Dropout(p=0.3)

In [40]:
x = torch.full((20,), 5.0)
x

tensor([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
        5., 5.])

In [41]:
myd(x)

tensor([7.1429, 0.0000, 7.1429, 7.1429, 0.0000, 7.1429, 7.1429, 7.1429, 7.1429,
        0.0000, 7.1429, 0.0000, 7.1429, 7.1429, 7.1429, 7.1429, 0.0000, 7.1429,
        7.1429, 7.1429])

In [42]:
d(x)

tensor([7.1429, 7.1429, 7.1429, 7.1429, 0.0000, 7.1429, 0.0000, 7.1429, 7.1429,
        7.1429, 0.0000, 7.1429, 7.1429, 7.1429, 7.1429, 7.1429, 0.0000, 0.0000,
        0.0000, 7.1429])

In [27]:
p = 0.2
mask = (torch.rand_like(x) > p).float()
mask * x

tensor([5., 5., 5., 5., 5., 5., 5., 5., 0., 0.])

In [34]:
w = 5

w * p

1.0

In [35]:
w / p

25.0

In [36]:
25.0 * p

5.0

In [ ]:
# sigmoid
# tanh
# ReLU
# LeakyReLU
# Randomized ReLU
# Parameterized ReLU

In [43]:
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(10, 20)
        self.relu1 = nn.ReLU()
        self.drop1 = nn.Dropout(0.5)
        self.fc2 = nn.Linear(20, 10)
        self.relu2 = nn.ReLU()
        self.drop2 = nn.Dropout(0.5)
        self.fc_out = self.Linear(10, 5)

    def forward(self, x):
        x = self.relu1(self.fc1(x))
        x = self.drop1(x)
        x = self.relu2(self.fc2(x))
        x = self.drop2(x)
        return self.fc3(x)
