In [ ]:
from tensorflow.keras.datasets  import california_housing
housing = california_housing.load_data()
(X_train, y_train), (X_test, y_test) = housing

In [5]:
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense, Normalization, InputLayer

In [6]:
norm_layer = Normalization(name = 'norm_layer')
model = Sequential([
    InputLayer(shape=[8], name = 'input_layer'),
    norm_layer,
    Dense(100, activation='relu', name = 'hidden1'),
    Dense(100, activation='relu', name = 'hidden2'),
    Dense(100, activation='relu', name = 'hidden3'),
    Dense(1) #output layer
])

In [7]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ norm_layer (Normalization)      │ (None, 8)              │            17 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ hidden1 (Dense)                 │ (None, 100)            │           900 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ hidden2 (Dense)                 │ (None, 100)            │        10,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ hidden3 (Dense)                 │ (None, 100)            │        10,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 21,218 (82.89 KB)

 Trainable params: 21,201 (82.82 KB)

 Non-trainable params: 17 (72.00 B)

In [25]:
norm_layer.adapt(X_train)

In [26]:
norm_layer.get_weights()

[array([-119.56227  ,   35.625397 ,   28.65413  , 2644.7268   ,
         539.5743   , 1433.2728   ,  501.45834  ,    3.8701892],
       dtype=float32),
 array([4.0044060e+00, 4.5356297e+00, 1.5868558e+02, 4.8844355e+06,
        1.8159067e+05, 1.3370920e+06, 1.5020797e+05, 3.6010580e+00],
       dtype=float32),
 np.int64(0)]

In [27]:
from tensorflow.keras.optimizers import Adam, SGD

In [28]:
optimizer = Adam(learning_rate=0.0001)
model.compile(optimizer=optimizer, loss='mse', metrics=['RootMeanSquaredError'])
history = model.fit(X_train, y_train, epochs=20, validation_split=0.2)

Epoch 1/20
413/413 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - RootMeanSquaredError: 236474.4844 - loss: 55920185344.0000 - val_RootMeanSquaredError: 238059.5156 - val_loss: 56672329728.0000
Epoch 2/20
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - RootMeanSquaredError: 236050.9219 - loss: 55720034304.0000 - val_RootMeanSquaredError: 237060.3281 - val_loss: 56197599232.0000
Epoch 3/20
413/413 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - RootMeanSquaredError: 233920.9844 - loss: 54719029248.0000 - val_RootMeanSquaredError: 233471.5469 - val_loss: 54508961792.0000
Epoch 4/20
413/413 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - RootMeanSquaredError: 228320.3594 - loss: 52130189312.0000 - val_RootMeanSquaredError: 225558.2188 - val_loss: 50876510208.0000
Epoch 5/20
413/413 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - RootMeanSquaredError: 217702.1094 - loss: 47394205696.0000 - val_RootMeanSquaredError: 212042.3594 - val_loss: 44961964032.0000
Epoch 6/20
413/413 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - RootMeanSquaredError: 201495.1406 - 

In [29]:
y_train[:5]

array([252300., 146900., 290900., 141300., 500001.], dtype=float32)

In [38]:
y_pred = model.predict(X_train)

516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step


In [39]:
model.evaluate(X_train, y_train)

516/516 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - RootMeanSquaredError: 92798.3984 - loss: 8611543040.0000


[8611543040.0, 92798.3984375]

In [41]:
from tensorflow.keras.metrics import R2Score

In [42]:
score = R2Score()
score.update_state(y_train, y_pred)

In [43]:
score.result()

<tf.Tensor: shape=(), dtype=float32, numpy=0.3535255193710327>

## Functional API

In [2]:
from tensorflow.keras.datasets  import california_housing
housing = california_housing.load_data()
(X_train, y_train), (X_test, y_test) = housing

In [1]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Normalization, Input, Concatenate

In [3]:
input_ = Input(shape=[8])
normalization_layer = Normalization()
hidden_layer1 = Dense(30, activation='relu')
hidden_layer2 = Dense(30, activation='relu')
concat_layer = Concatenate() 
output_layer = Dense(1)

normalized = normalization_layer(input_)
hidden1 = hidden_layer1(normalized)
hidden2 = hidden_layer2(hidden1)
concatenated = concat_layer([input_, hidden2])
output = output_layer(concatenated)

model = Model(inputs = [input_], outputs = [output])

In [4]:
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer         │ (None, 8)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ normalization       │ (None, 8)         │         17 │ input_layer[0][0] │
│ (Normalization)     │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense (Dense)       │ (None, 30)        │        270 │ normalization[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_1 (Dense)     │ (None, 30)        │        930 │ dense[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concatenate         │ (None, 38)        │          0 │ input_layer[0][0… │
│ (Concatenate)       │                   │            │ dense_1[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_2 (Dense)     │ (None, 1)         │         39 │ concatenate[0][0] │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 1,256 (4.91 KB)

 Trainable params: 1,239 (4.84 KB)

 Non-trainable params: 17 (72.00 B)

In [5]:
model.save('deep_and_wide_model.keras')

## Subclass API

In [1]:
from tensorflow.keras.datasets  import boston_housing
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Normalization, Input, Concatenate
housing = boston_housing.load_data()
(X_train, y_train), (X_test, y_test) = housing

57026/57026 ━━━━━━━━━━━━━━━━━━━━ 0s 3us/step


In [2]:
class MyModel(Model):
    def __init__(self, units=30, activation='relu', **kwargs):
        super().__init__(**kwargs)
        self.norm_layer=Normalization()
        self.hidden1=Dense(units, activation)
        self.hidden2=Dense(units, activation)
        self.out=Dense(1)
    def call(self, X):
        X=self.norm_layer(X)
        X=self.hidden1(X)
        X=self.hidden2(X)
        X=self.out(X)
        return X
my_model = MyModel(units=50)
my_model.norm_layer.adapt(X_train)

In [4]:
from tensorflow.keras.optimizers import Adam
optimizer = Adam(learning_rate = 0.001)
my_model.compile(optimizer=optimizer, loss='mse', metrics=['RootMeanSquaredError'])
history=my_model.fit(X_train, y_train, epochs=10, validation_split=0.2)

Epoch 1/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - RootMeanSquaredError: 3.3486 - loss: 11.2128 - val_RootMeanSquaredError: 4.1640 - val_loss: 17.3388
Epoch 2/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - RootMeanSquaredError: 3.2966 - loss: 10.8677 - val_RootMeanSquaredError: 4.1880 - val_loss: 17.5390
Epoch 3/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - RootMeanSquaredError: 3.2446 - loss: 10.5275 - val_RootMeanSquaredError: 4.1695 - val_loss: 17.3845
Epoch 4/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - RootMeanSquaredError: 3.2060 - loss: 10.2785 - val_RootMeanSquaredError: 4.1764 - val_loss: 17.4423
Epoch 5/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - RootMeanSquaredError: 3.1879 - loss: 10.1626 - val_RootMeanSquaredError: 4.1253 - val_loss: 17.0182
Epoch 6/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - RootMeanSquaredError: 3.1764 - loss: 10.0894 - val_RootMeanSquaredError: 4.1367 - val_loss: 17.1127
Epoch 7/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - RootMeanSquaredError: 3.1454 -

In [5]:
out=my_model(X_train)

In [6]:
out

<tf.Tensor: shape=(404, 1), dtype=float32, numpy=
array([[15.180723 ],
       [40.888878 ],
       [37.39276  ],
       [21.19357  ],
       [19.653824 ],
       [17.711615 ],
       [13.205507 ],
       [12.746481 ],
       [15.443058 ],
       [14.508023 ],
       [14.400738 ],
       [11.854289 ],
       [23.106153 ],
       [19.562618 ],
       [17.325571 ],
       [ 7.82253  ],
       [51.916397 ],
       [25.535717 ],
       [24.414114 ],
       [23.684076 ],
       [12.485054 ],
       [29.140364 ],
       [32.18181  ],
       [28.37289  ],
       [19.09825  ],
       [15.497777 ],
       [18.32594  ],
       [32.669292 ],
       [14.327441 ],
       [17.074621 ],
       [21.837294 ],
       [16.993465 ],
       [13.921358 ],
       [20.199615 ],
       [34.52088  ],
       [23.762325 ],
       [13.161884 ],
       [14.652363 ],
       [20.89611  ],
       [18.622124 ],
       [20.159496 ],
       [26.229715 ],
       [22.38406  ],
       [17.49505  ],
       [16.664345 ],
     

In [ ]:
my_model.predict()